/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventorysoftware.LogIn;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseen Ameer
 */
public class barang_keluar extends javax.swing.JFrame {
 
    private String tgl;
    
     int x;

    /**
     * Creates new form NewSignin
     */
    public barang_keluar() {
        
        initComponents();
        koneksi_database();
        kosongkan_text();
        AutoNumber();
        tampil_combo_barang();
        tampil_combo_customer();
        tampil_data();
        view_barang_keluar("SELECT * FROM barang_keluar");
        this.setLocationRelativeTo(null);
 
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_inven5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_keluar = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        kode_keluar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        kode_barang = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jumlah1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        btn_exit1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        kode_customer = new javax.swing.JComboBox<>();
        nama_customer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(153, 204, 0));
        jLabel_inven5.setText("Input Data Barang Keluar");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 490, 50));

        jScrollPane1.setForeground(new java.awt.Color(103, 170, 22));

        tabel_keluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_keluar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 1130, 260));

        txtcari.setForeground(new java.awt.Color(153, 204, 0));
        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 310, 30));

        btn_exit.setForeground(new java.awt.Color(153, 204, 0));
        btn_exit.setText("Hitung");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 100, 30));

        btn_delete.setForeground(new java.awt.Color(153, 204, 0));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 100, 30));

        cmb_cari.setForeground(new java.awt.Color(153, 204, 0));
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode keluar", "Nama Barang" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 200, 30));

        btn_cancel.setForeground(new java.awt.Color(153, 204, 0));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 100, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 204, 0));
        jLabel2.setText("Cari Berdasarkan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 140, 30));

        btn_save.setForeground(new java.awt.Color(153, 204, 0));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 30));

        kode_keluar.setForeground(new java.awt.Color(153, 204, 0));
        kode_keluar.setText("kode keluar");
        kode_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_keluarActionPerformed(evt);
            }
        });
        kode_keluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_keluarKeyPressed(evt);
            }
        });
        jPanel1.add(kode_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 0));
        jLabel3.setText("Kode Keluar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 30));

        menu1.setBackground(new java.awt.Color(153, 0, 0));
        menu1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(21, 25, 28));
        menu1.setText("Menu");
        menu1.setBorder(null);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.setFocusPainted(false);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 60, 30));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton11.setToolTipText("Close");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 40, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 0));
        jLabel6.setText("Persediaan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 30));

        jumlah.setForeground(new java.awt.Color(153, 204, 0));
        jumlah.setText("jumlah");
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 350, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 0));
        jLabel7.setText("Tanggal Keluar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 204, 0));
        jLabel8.setText("Kode Barang");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, 30));

        nama_barang.setForeground(new java.awt.Color(153, 204, 0));
        nama_barang.setText("barang");
        nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangActionPerformed(evt);
            }
        });
        jPanel1.add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 260, 30));

        kode_barang.setForeground(new java.awt.Color(153, 204, 0));
        kode_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pilih Kode Barang==" }));
        kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_barangActionPerformed(evt);
            }
        });
        jPanel1.add(kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 30));

        tanggal.setForeground(new java.awt.Color(153, 204, 0));
        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 270, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 204, 0));
        jLabel9.setText("Jumlah Keluar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 180, 30));

        jumlah1.setForeground(new java.awt.Color(153, 204, 0));
        jumlah1.setText("jumlah keluar");
        jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah1ActionPerformed(evt);
            }
        });
        jPanel1.add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 0));
        jLabel10.setText("Total Persediaan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 180, 30));

        total.setForeground(new java.awt.Color(153, 204, 0));
        total.setText("total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 350, 30));

        btn_exit1.setForeground(new java.awt.Color(153, 204, 0));
        btn_exit1.setText("EXIT");
        btn_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 204, 0));
        jLabel11.setText("Nama Barang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 30));

        kode_customer.setForeground(new java.awt.Color(153, 204, 0));
        kode_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pilih Kode Customer==" }));
        kode_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_customerActionPerformed(evt);
            }
        });
        jPanel1.add(kode_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, 30));

        nama_customer.setForeground(new java.awt.Color(153, 204, 0));
        nama_customer.setText("nama_customer");
        nama_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_customerActionPerformed(evt);
            }
        });
        jPanel1.add(nama_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 0));
        jLabel12.setText("Kode Customer");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 204, 0));
        jLabel13.setText("Nama Customer");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        String kategori = cmb_cari.getSelectedItem().toString();
        String vkategori;
        if(kategori=="Kode Keluar"){
            vkategori ="kode_keluar";
        }else if(kategori=="Nama Customer"){
            vkategori ="nama_customer";
        }else if(kategori=="Nama Barang"){
            vkategori ="nama_barang";
        }else{
            vkategori ="kode_keluar";
        }
        view_barang_keluar ("SELECT * FROM barang_keluar WHERE "+vkategori+" LIKE '%"+txtcari.getText()+"%' ");
    }//GEN-LAST:event_txtcariCaretUpdate

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       
       int a = Integer.parseInt(jumlah.getText());
       int b = Integer.parseInt(jumlah1.getText());
       
       x = a-b;
       total.setText(Integer.toString(x));
        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            sql = "DELETE FROM barang_keluar WHERE kode_keluar='"+kode_keluar.getText()+"' ";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }

        if(kode_keluar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode Barang Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "delete FROM barang_keluar where kode_keluar='"+kode_keluar.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Dihapus !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        kosongkan_text();
        AutoNumber();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            sql = "INSERT INTO barang_keluar VALUES ('"+kode_keluar.getText()+
            "','"+nama_customer.getText()+
            "','"+nama_barang.getText()+
            "','"+tgl+
            "','"+jumlah1.getText()+
           
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan...");
            kosongkan_text();
            AutoNumber();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal..."+e);
        }

        if(kode_keluar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode Keluar Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "update barang_keluar set nama_barang='"+nama_barang.getText()+
                "' where kode_keluar='"+kode_keluar.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Diupdate !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Diupdate !"+e);
            }
            kosongkan_text();
        }
        
        
         try {  
            sql = "UPDATE barang_masuk SET jumlah='"+x+
            "' WHERE kode_barang='" + kode_barang.getSelectedItem()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Sukses...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }
        view_barang_keluar("SELECT * FROM barang_keluar");
    }//GEN-LAST:event_btn_saveActionPerformed

    private void kode_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_keluarActionPerformed
     
    }//GEN-LAST:event_kode_keluarActionPerformed

    private void kode_keluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_keluarKeyPressed
       
    }//GEN-LAST:event_kode_keluarKeyPressed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangActionPerformed

    private void kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_barangActionPerformed
        tampil_data_barang();
        tampil_data_barang1();
    }//GEN-LAST:event_kode_barangActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        if(tanggal.getDate()!=null){
            SimpleDateFormat format_tanggal = new  SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tanggal.format(tanggal.getDate());
      }
    }//GEN-LAST:event_tanggalPropertyChange

    private void jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void btn_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exit1ActionPerformed

    private void kode_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_customerActionPerformed
        tampil_data_customer();
    }//GEN-LAST:event_kode_customerActionPerformed

    private void nama_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang_keluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_exit1;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JComboBox<String> kode_barang;
    private javax.swing.JComboBox<String> kode_customer;
    private javax.swing.JTextField kode_keluar;
    private javax.swing.JButton menu1;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_customer;
    private javax.swing.JTable tabel_keluar;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
try {
    Class.forName("com.mysql.jdbc.Driver");
    System.out.println("Driver Ditemukan...");
    try {
        String url = "jdbc:mysql://localhost:3306/inventory?user=root&password=";
        con = DriverManager.getConnection(url);
        System.out.println("Terkoneksi...");
    } catch (SQLException e){
        System.err.println("Tidak Terkoneksi...");
    }
} catch (ClassNotFoundException e) {
    System.err.println("Driver Tidak Ada...");
}
}

private void kosongkan_text() {  
nama_barang.setText("");
jumlah.setText("");
nama_barang.setText("");
kode_keluar.requestFocus();
nama_customer.setText("");
jumlah.setText("");
jumlah1.setText("");
total.setText("");
}

private void AutoNumber(){
try {
sql  = "SELECT MAX(RIGHT(kode_keluar,4)) AS no_auto FROM barang_keluar";
stat = con.createStatement();
rs   = stat.executeQuery(sql);
if(rs.next()){
String no_auto, nol_plus;
int p;
no_auto = Integer.toString(rs.getInt(1)+1);
p = no_auto.length();
nol_plus = "";
for(int i=1;i<=4-p;i++){
nol_plus = nol_plus + "0";    
}
kode_keluar.setText("BK"+nol_plus+no_auto);
}
} catch (Exception e) {
    kode_keluar.setText("BK0001");    
}          
}

private void tampil_data(){
try {
    sql  = "SELECT * FROM barang_masuk WHERE kode_barang='"+kode_keluar.getText()+"'";
    stat = con.createStatement();
    rs   = stat.executeQuery(sql);
    if(rs.next()){
    nama_barang.setText(rs.getString("nama_barang"));
    
  
    btn_delete.setEnabled(true);
    btn_save.setEnabled(false);
    } else{
    kosongkan_text();
    }
    rs.close();
    stat.close();
    }
catch (Exception e) {
}
}


private void view_barang_keluar (String sql){
Object[] header = {"Kode Keluar"," Nama Customer", "Nama Barang", "Tanggal Keluar","Jumlah Keluar"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
tabel_keluar.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
 
  while (rs.next()){
  String[] Data = {
      
      rs.getString("kode_keluar"),
      rs.getString("nama_customer"),
      rs.getString("nama_barang"),
      rs.getString("tanggal_keluar"),
      rs.getString("jumlah_keluar"),

  };  
  tabel.addRow(Data);
 
  }
 
  tabel_keluar.getColumnModel().getColumn(0).setPreferredWidth(50);
  tabel_keluar.getColumnModel().getColumn(1).setPreferredWidth(200);
  tabel_keluar.getColumnModel().getColumn(2).setPreferredWidth(200);
  tabel_keluar.getColumnModel().getColumn(3).setPreferredWidth(200);
} catch (Exception e) {
  System.err.println (e);
}
}

private void tampil_combo_barang(){
    try {
        Statement stat = con.createStatement();
        String sql = "select kode_barang from barang_masuk order by kode_barang asc";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            kode_barang.addItem((String) ob[0]);
        }
        res.close();
        stat.close();
    } catch (Exception e) {
    }
}

private void tampil_data_barang(){
    try {
        Statement stat = con.createStatement();
        String sql = "select nama_barang from barang_masuk where kode_barang='"+kode_barang.getSelectedItem()+"'";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
           
            nama_barang.setText((String) ob[0]);
         
            
            
        }
        res.close();
        stat.close();
    } catch (Exception e) {
    }
}


private void tampil_data_barang1(){
    try {
        Statement stat = con.createStatement();
        String sql = "select jumlah from barang_masuk where kode_barang='"+kode_barang.getSelectedItem()+"'";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
           
            jumlah.setText((String) ob[0]);
            
            
        }
        res.close();
        stat.close();
    } catch (Exception e) {
    }
}


private void tampil_combo_customer(){
    try {
        Statement stat = con.createStatement();
        String sql = "select kode_customer from customer order by kode_customer asc";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            kode_customer.addItem((String) ob[0]);
        }
        res.close();
        stat.close();
    } catch (Exception e) {
    }
}

private void tampil_data_customer(){
    try {
        Statement stat = con.createStatement();
        String sql = "select nama_customer from customer where kode_customer='"+kode_customer.getSelectedItem()+"'";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
           
            nama_customer.setText((String) ob[0]);
            
            
        }
        res.close();
        stat.close();
    } catch (Exception e) {
    }
}


}
