/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventorysoftware.LogIn;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseen Ameer
 */
public class data_suplier extends javax.swing.JFrame {
 

    /**
     * Creates new form NewSignin
     */
    public data_suplier() {
        
        initComponents();
        koneksi_database();
        kosongkan_text();
        AutoNumber();
        tampil_data();
        view_supplier("SELECT * FROM supplier");
        this.setLocationRelativeTo(null);
 
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_inven5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_suplier = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Data Supplier");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 50));

        jScrollPane1.setForeground(new java.awt.Color(103, 170, 22));

        tabel_suplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_suplier);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1120, 280));

        txtcari.setForeground(new java.awt.Color(103, 170, 22));
        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 340, 30));

        btn_delete.setForeground(new java.awt.Color(103, 170, 22));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 130, 30));

        btn_update.setForeground(new java.awt.Color(103, 170, 22));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 30));

        cmb_cari.setForeground(new java.awt.Color(103, 170, 22));
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Supplier", "Nama Supplier" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 230, 30));

        btn_cancel.setForeground(new java.awt.Color(103, 170, 22));
        btn_cancel.setText("CLEAR");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 170, 22));
        jLabel2.setText("Cari Berdasarkan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 30));

        btn_save.setForeground(new java.awt.Color(103, 170, 22));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, 30));

        kode.setForeground(new java.awt.Color(103, 170, 22));
        kode.setText("txtkode");
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodeKeyPressed(evt);
            }
        });
        jPanel1.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 170, 22));
        jLabel3.setText("Kode Supplier");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 170, 22));
        jLabel4.setText("Nama Supplier");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 30));

        menu1.setBackground(new java.awt.Color(152, 201, 45));
        menu1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(21, 25, 28));
        menu1.setText("Menu");
        menu1.setBorder(null);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.setFocusPainted(false);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 60, 30));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton11.setToolTipText("Close");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 40, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(103, 170, 22));
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 30));

        nama.setForeground(new java.awt.Color(103, 170, 22));
        nama.setText("nama");
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 350, 30));

        alamat.setForeground(new java.awt.Color(103, 170, 22));
        alamat.setText("alamat");
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 350, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(103, 170, 22));
        jLabel8.setText("No hp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 30));

        nohp.setForeground(new java.awt.Color(103, 170, 22));
        nohp.setText("nohp");
        jPanel1.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        String kategori = cmb_cari.getSelectedItem().toString();
        String vkategori;
        if(kategori=="Kode Supplier"){
            vkategori ="kode_supplier";
        }else if(kategori=="Nama Supplier"){
            vkategori ="nama_supplier";
        }else{
            vkategori ="kode_supplier";
        }
        view_supplier ("SELECT * FROM supplier WHERE "+vkategori+" LIKE '%"+txtcari.getText()+"%' ");
    }//GEN-LAST:event_txtcariCaretUpdate

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            sql = "DELETE FROM supplier WHERE kode_supplier='"+kode.getText()+"' ";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }

        if(kode.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode penyakit Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "delete FROM supplier where kode_supplier='"+kode.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Dihapus !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            sql = "UPDATE supplier SET nama_supplier='"+nama.getText()+
            "' WHERE kode_supplier='" + kode.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Sukses...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }
        
        view_supplier("SELECT * FROM supplier");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        kosongkan_text();
        AutoNumber();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            sql = "INSERT INTO supplier VALUES ('"+kode.getText()+
            "','"+nama.getText()+
            "','"+alamat.getText()+
            "','"+nohp.getText()+
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan...");
            kosongkan_text();
            AutoNumber();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal..."+e);
        }

        if(kode.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode supplier Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "update supplier set nama_supplier='"+nama.getText()+
                "' where kode_supplier='"+kode.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Diupdate !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Diupdate !"+e);
            }
            kosongkan_text();
        }
    view_supplier("SELECT * FROM supplier");
    }//GEN-LAST:event_btn_saveActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
     
    }//GEN-LAST:event_kodeActionPerformed

    private void kodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyPressed
       
    }//GEN-LAST:event_kodeKeyPressed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_suplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kode;
    private javax.swing.JButton menu1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTable tabel_suplier;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

   private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
try {
    Class.forName("com.mysql.jdbc.Driver");
    System.out.println("Driver Ditemukan...");
    try {
        String url = "jdbc:mysql://localhost:3306/inventory?user=root&password=";
        con = DriverManager.getConnection(url);
        System.out.println("Terkoneksi...");
    } catch (SQLException e){
        System.err.println("Tidak Terkoneksi...");
    }
} catch (ClassNotFoundException e) {
    System.err.println("Driver Tidak Ada...");
}
}

private void kosongkan_text() {  
nama.setText("");
alamat.setText("");
nohp.setText("");
kode.requestFocus();
}

private void AutoNumber(){
try {
sql  = "SELECT MAX(RIGHT(kode_supplier,4)) AS no_auto FROM supplier";
stat = con.createStatement();
rs   = stat.executeQuery(sql);
if(rs.next()){
String no_auto, nol_plus;
int p;
no_auto = Integer.toString(rs.getInt(1)+1);
p = no_auto.length();
nol_plus = "";
for(int i=1;i<=4-p;i++){
nol_plus = nol_plus + "0";    
}
kode.setText("S"+nol_plus+no_auto);
}
} catch (Exception e) {
    kode.setText("S0001");    
}          
}

private void tampil_data(){
try {
    sql  = "SELECT * FROM supplier WHERE kode_supplier='"+kode.getText()+"'";
    stat = con.createStatement();
    rs   = stat.executeQuery(sql);
    if(rs.next()){
    nama.setText(rs.getString("nama_supplier"));
    alamat.setText(rs.getString("alamat"));
    nohp.setText(rs.getString("no_hp"));
    
    btn_update.setEnabled(true);
    btn_delete.setEnabled(true);
    btn_save.setEnabled(false);
    } else{
    kosongkan_text();
    }
    rs.close();
    stat.close();
    }
catch (Exception e) {
}
}


private void view_supplier (String sql){
Object[] header = {"Kode Supplier","Nama Supplier","Alamat Supplier","No Hp"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
tabel_suplier.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
 
  while (rs.next()){
  String[] Data = {
      
      rs.getString("kode_supplier"),
      rs.getString("nama_supplier"),
      rs.getString("alamat"),
      rs.getString("no_hp"),
  };  
  tabel.addRow(Data);
 
  }
 
  tabel_suplier.getColumnModel().getColumn(0).setPreferredWidth(100);
  tabel_suplier.getColumnModel().getColumn(1).setPreferredWidth(150);
  tabel_suplier.getColumnModel().getColumn(2).setPreferredWidth(400);
  tabel_suplier.getColumnModel().getColumn(3).setPreferredWidth(400);
} catch (Exception e) {
  System.err.println (e);
}
}

}
